# Generated by Django 5.2.3 on 2025-06-30 10:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "first_name",
                    models.CharField(blank=True, help_text="Введите имя", max_length=30, verbose_name="Имя"),
                ),
                (
                    "last_name",
                    models.CharField(blank=True, help_text="Введите фамилию", max_length=30, verbose_name="Фамилия"),
                ),
                (
                    "birth_date",
                    models.DateField(
                        blank=True, help_text="Введите дату рождения", null=True, verbose_name="Дата рождения"
                    ),
                ),
                (
                    "profile_picture",
                    models.ImageField(
                        blank=True,
                        help_text="Добавьте фото профиля",
                        upload_to="profile_pictures/",
                        verbose_name="Фото профиля",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
                ),
            ],
        ),
    ]
