# Generated by Django 4.2.2 on 2025-07-07 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_user_options_user_is_blocked"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={
                "permissions": [
                    ("can_block_user", "Может блокировать пользователя"),
                    ("can_view_users", "Может просмотреть пользователей"),
                ],
                "verbose_name": "Пользователь",
                "verbose_name_plural": "Пользователи",
            },
        ),
    ]
