# Generated by Django 5.2.3 on 2025-06-30 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Recipient",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "email",
                    models.EmailField(help_text="Введите email", max_length=254, unique=True, verbose_name="Email"),
                ),
                (
                    "name",
                    models.CharField(help_text="Укажите фамилию, имя, отчество", max_length=250, verbose_name="Ф.И.О"),
                ),
                ("comment", models.TextField(help_text="Напишите комментарий", verbose_name="Комментарий")),
            ],
            options={
                "verbose_name": "получатель",
                "verbose_name_plural": "получатели",
                "ordering": ["email", "name"],
            },
        ),
    ]
