# Generated by Django 5.2.3 on 2025-06-30 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Message",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "subject_letter",
                    models.CharField(help_text="Укажите тему письма", max_length=200, verbose_name="Тема письма"),
                ),
                ("body_letter", models.TextField(help_text="Укажите текст письма", verbose_name="Тело письма")),
            ],
            options={
                "verbose_name": "сообщение",
                "verbose_name_plural": "сообщения",
                "ordering": ["subject_letter"],
            },
        ),
    ]
