# Generated by Django 5.2.3 on 2025-06-30 10:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0002_message"),
    ]

    operations = [
        migrations.CreateModel(
            name="Mailing",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "first_send_datetime",
                    models.DateTimeField(
                        blank=True,
                        help_text="Дата и время первой отправки (может быть пустым, если рассылка еще не запущена)",
                        null=True,
                        verbose_name="Дата и время первой отправки",
                    ),
                ),
                (
                    "end_send_datetime",
                    models.DateTimeField(
                        blank=True,
                        help_text="Дата и время окончания отправки "
                                  "(может быть пустым, если рассылка еще не завершена)",
                        null=True,
                        verbose_name="Дата и время окончания отправки",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("created", "Создана"), ("running", "Запущена"), ("completed", "Завершена")],
                        default="created",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                ("message", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="mailing.message")),
                ("recipient", models.ManyToManyField(to="mailing.recipient")),
            ],
            options={
                "verbose_name": "Рассылка",
                "verbose_name_plural": "Рассылки",
                "ordering": ["status"],
            },
        ),
    ]
