# Generated by Django 5.2.3 on 2025-06-30 10:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0003_mailing"),
    ]

    operations = [
        migrations.CreateModel(
            name="MailingAttempt",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "attempt_datetime",
                    models.DateTimeField(help_text="Дата и время попытки", verbose_name="Дата и время попытки"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("successfully", "Успешно"), ("not successfully", "Не успешно")],
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                ("mail_server_response", models.TextField(verbose_name="Ответ почтового сервера")),
                ("mailing", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="mailing.mailing")),
            ],
            options={
                "verbose_name": "Попытка",
                "verbose_name_plural": "Попытки",
            },
        ),
    ]
