# Generated by Django 4.2.2 on 2025-07-01 11:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("mailing", "0005_mailing_user_message_user_recipient_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="mailingattempt",
            name="user",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="mailingattempt",
            name="attempt_datetime",
            field=models.DateTimeField(
                auto_now_add=True, help_text="Дата и время попытки", verbose_name="Дата и время попытки"
            ),
        ),
    ]
