# Generated by Django 4.2.2 on 2025-07-02 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0006_mailingattempt_user_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mailing",
            options={
                "ordering": ["status"],
                "permissions": [
                    ("can_set_mailing_status", "Можно установить статус рассылки"),
                    ("can_disable_mailing", "Может отключать рассылку"),
                ],
                "verbose_name": "Рассылка",
                "verbose_name_plural": "Рассылки",
            },
        ),
        migrations.AlterModelOptions(
            name="message",
            options={
                "ordering": ["subject_letter"],
                "permissions": [("can_view_message", "Можно просмотреть сообщение")],
                "verbose_name": "сообщение",
                "verbose_name_plural": "сообщения",
            },
        ),
        migrations.AlterModelOptions(
            name="recipient",
            options={
                "ordering": ["email", "name"],
                "permissions": [("can_view_recipient", "Может просматривать получателя")],
                "verbose_name": "получатель",
                "verbose_name_plural": "получатели",
            },
        ),
    ]
