# Generated by Django 4.2.2 on 2025-07-03 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0007_alter_mailing_options_alter_message_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mailing",
            options={
                "ordering": ["status"],
                "permissions": [
                    ("can_set_mailing_status", "Можно установить статус рассылки"),
                    ("can_disable_mailing", "Может отключать рассылку"),
                    ("can_complete_mailing", "Может завершать рассылку"),
                ],
                "verbose_name": "Рассылка",
                "verbose_name_plural": "Рассылки",
            },
        ),
        migrations.AlterField(
            model_name="mailing",
            name="status",
            field=models.CharField(
                choices=[("created", "Создана"), ("running", "Запущена"), ("completed", "Завершена")],
                default="Создана",
                max_length=20,
                verbose_name="Статус",
            ),
        ),
    ]
