# Generated by Django 4.2.2 on 2025-07-06 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0008_alter_mailing_options_alter_mailing_status"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mailing",
            options={
                "ordering": ["status"],
                "permissions": [
                    ("can_set_mailing_status", "Можно установить статус рассылки"),
                    ("can_disable_mailing", "Может отключать рассылку"),
                    ("can_complete_mailing", "Может завершать рассылку"),
                    ("can_view_all_mailings", "Может просмотреть все рассылки"),
                ],
                "verbose_name": "Рассылка",
                "verbose_name_plural": "Рассылки",
            },
        ),
    ]
